name: Build Flet APK
on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flet & Requests
        run: |
          pip install flet requests

      - name: Build APK
        env:
          NVIDIA_API_KEY: ${{ secrets.NVIDIA_KEY }}
        # 🟢 زدنا --no-interactive باش السيستم يوافق على تحميل Flutter SDK بوحدو بلا ما يسول
        run: |
          flet build apk --no-interactive

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nibras-apk
          path: build/apk/*.apk
